language: c
compiler:
  - clang
  - gcc

os:
  - linux
#  - osx

env:
  - DEBUG=0
  - DEBUG=1

# needed for libuv
before_install:
  - git submodule update --init --recursive
install:
  - sudo apt-get update -qq
#  - sudo apt-get install -qq libdisasm-dev

script: make config CC=$CC DEBUG=$DEBUG; make && make -j1 test

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"

# DEFAULT TEMPLATE
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
